Repository lucianmot/f.rest, pull requests merged in 2019-08, with the labels that each got.

#1 Feature echo
  .gitignore
  README.md
  echo_test.py
  forest.py
  tokeniser_test.py
Labels: documentation, enhancement, good first issue, help wanted

#2 Admin tasks
  .gitignore
  Interpreterv2.jpg
  README.md
Labels: documentation, enhancement, good first issue

#5 CHORE: updates continous integration set-up
  .travis.yml
Labels: documentation, enhancement, good first issue

#4 CHORE: README updated after refactor
  README.md
Labels: documentation, enhancement, wontfix

#6 CHORE: modifies ci setup
  .travis.yml
  README.md
Labels: documentation, enhancement, help wanted, wontfix

#8 added extra script line in travis.yml to fix ci pass-fail sequence
  .travis.yml
Labels: bug, enhancement, good first issue, wontfix

#10 Feature parser
  forest.py
  interpreter_test.py
Labels: documentation, enhancement

#11 Syntax ideas
  .travis.yml
  key_words.md
  tokeniser_test.py
Labels: documentation, good first issue, help wanted

#12 Feature interpreter
  README.md
  forest.py
  interpreter_test.py
Labels: bug, documentation, enhancement, help wanted

#13 Tokenising
  forest.py
  interpreter_test.py
  tokeniser_test.py
Labels: bug, documentation, enhancement, help wanted, wontfix

#14 FEATURE: Owl operator added to tokens
  forest.py
  interpreter_test.py
Labels: documentation, enhancement

#15 Not equal
  forest.py
  interpreter_test.py
Labels: bug, enhancement, wontfix

#17 Grammar rule3
  forest.py
  interpreter_test.py
Labels: bug, enhancement

#16 Crow operator
  forest.py
  interpreter_test.py
Labels: enhancement, good first issue, wontfix

#18 IDEA: ideas for user-friendly forest-themed error messages
  key_words.md
Labels: documentation, good first issue

#23 Feature parser expansion
  forest.py
  interpreter_test.py
Labels: documentation, enhancement

#22 Errors method
  forest.py
  key_words.md
Labels: enhancement, ʕ·ᴥ·ʔ

#21 Var assign
  forest.py
  interpreter_test.py
Labels: bug, enhancement

#25 feature: pass feature tests and random errors
  forest.py
  interpreter_test.py
Labels: ʕ·ᴥ·ʔ

#26 feature: add shell script
  forest.py
Labels: enhancement

#27 REFACTOR: added modulus of integers grammara rule
  forest.py
Labels: bug, enhancement, ʕ·ᴥ·ʔ
